[env:ttgo-t1]
platform = espressif32
board = ttgo-t1
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_resetmethod = nodemcu
lib_deps =
  bodmer/TFT_eSPI @ ^2.5.0
build_flags =
  -DUSER_SETUP_LOADED
  -DUSER_SETUP_ID=25
  -DST7789_DRIVER
  -DTFT_WIDTH=135
  -DTFT_HEIGHT=240
  -DTFT_MOSI=19
  -DTFT_SCLK=18
  -DTFT_CS=5
  -DTFT_DC=16
  -DTFT_RST=23
  -DTFT_BL=4
  -DTFT_BACKLIGHT_ON=HIGH
  -DCGRAM_OFFSET
  -DLOAD_GLCD
  -DLOAD_FONT2
  -DLOAD_FONT4
  -DLOAD_GFXFF
  -DSMOOTH_FONT
  -DSPI_FREQUENCY=40000000
upload_flags =
  --before=no_reset
  --after=hard_reset
  --chip=esp32